# Generated by Django 4.2 on 2023-07-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='memes/')),
                ('caption1', models.CharField(blank=True, max_length=200, null=True)),
                ('caption2', models.CharField(blank=True, max_length=200, null=True)),
                ('caption3', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
